# Generated by Django 4.2.4 on 2023-09-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='excerpt',
            new_name='field',
        ),
        migrations.RemoveField(
            model_name='people',
            name='title',
        ),
        migrations.AddField(
            model_name='books',
            name='name',
            field=models.CharField(default='hello', max_length=50),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default='hello', max_length=50),
        ),
    ]
